#!/usr/bin/env python3
try:
    from pyrogram import Client
except Exception as e:
    print(e)
    print('\nInstall Pyrogram: pip3 install pyrogram')
    exit(1)

print('Enter your app creds from my.telegram.org/apps below.')
API_KEY = int(input("Enter API KEY: "))
API_HASH = input("Enter API HASH: ")
with Client(name='ZEE', api_id=API_KEY, api_hash=API_HASH, in_memory=True) as app:
    app.send_message("me",
                     "**Pyrogram Session String**:\n\n"
                     f"||{app.export_session_string()}||\n\n"
                     "**Do not share this anywhere!**\n\n"
                     "**Generated by @Z_Mirror**"
                     )
    print(
        "Your Pyrogram session string has been sent to "
        "Saved Messages of your Telegram account!"
    )